# Generated by Django 4.2.17 on 2024-12-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articuloWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloArticulo', models.CharField(blank=True, max_length=128, null=True)),
                ('contenidoArticulo', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='temaWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTema', models.CharField(blank=True, max_length=128, null=True)),
                ('descripcionTema', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
