# Generated by Django 4.2.17 on 2024-12-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulowiki',
            old_name='contenidoArticulo',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='articulowiki',
            old_name='tituloArticulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='temawiki',
            old_name='descripcionTema',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='temawiki',
            old_name='nombreTema',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='articulowiki',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiApp.temawiki'),
        ),
    ]
