# Generated by Django 4.2.17 on 2024-12-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0003_remove_articulowiki_contenido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulowiki',
            name='tema',
        ),
        migrations.AddField(
            model_name='articulowiki',
            name='temaR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiApp.temawiki'),
        ),
    ]
