# Generated by Django 4.2.17 on 2024-12-10 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0006_alter_articulowiki_temar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulowiki',
            name='temaR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='wikiApp.temawiki'),
        ),
    ]
